print('enter the first number to add:')
first = input()
print('enter the sencond number to add:')
sencond = input()
print('enter the third number to add:')
third = input()
print('the sum is' + first + sencond + third)
